# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Invalid zipcode', regex='^[0-9]{5}-?[0-9]{3}')])),
            ],
        ),
    ]
